import { pageMetadata } from "@/lib/site";
export const metadata = pageMetadata("Website Information", "How to use the Dr. Drunk website, contact the team, control motion and explore the original brand guides.", "/site-info");
export default function SiteInformation() {
  return <main id="main"><header className="utility-intro section-pad"><a className="eyebrow" href="/">HOME /</a><h1>The little<br /><span className="script">details.</span></h1><p>A few useful things about this website.</p></header><section className="site-information section-pad">
    <article><h2>Enquiries & bookings</h2><p>Email and tasting links open your email application. Telephone links open your calling application. This website does not take payments or confirm bookings. Agree event details, availability and pricing directly with <a href="/contact">the team</a>.</p></article>
    <article><h2>Privacy & external links</h2><p>The website does not include an enquiry database, advertising trackers or an embedded social feed. Copy page link uses your browser clipboard only after you press the button. Email, Instagram and the hosting service operate separately and may process information under their own terms and privacy practices. Only include information you want to share when contacting the team.</p></article>
    <article><h2>Motion & accessibility</h2><p>The site respects your device’s reduced-motion preference. The 3D scenes and decorative background have pause controls; smaller screens use photographs in place of the 3D canvas. Navigation, cocktail tabs, FAQs and the gallery support keyboard use. If something is difficult to use, <a href="mailto:Docdrunkofficial@gmail.com">tell us by email</a>.</p></article>
    <article><h2>Images & source material</h2><p>Photographs and brand material come from the supplied Dr. Drunk decks and event archive. The drawings and 3D objects interpret their visual language. Explore the <a href="/about#guides">four original guides</a> for complete presentation boards and references. Menu ideas are inspiration for a conversation, not a live stock or price list.</p></article>
  </section></main>;
}
