const groups: [string, string, string[]][] = [
  [
    "safe",
    "Play It Safe",
    [
      "Amaretto Sour|Amaretto, egg white, bitters",
      "Guava Island|Rum, pink guava, coconut cream, kaffir",
      "Blue Job|Vodka, blue curaçao, pineapple, coconut cream",
      "Sojurita|Soju, tequila, triple sec, grapefruit",
      "Cgi Cgi|Gin, cucumber, lime",
      "Lychee All Over Me|Rum, kwai feh, edible flower",
      "Passion in My Pants|Vodka, passion fruit, gummy bear",
      "Mango Mangone|Gin, mango, Campari",
      "Pirates of Siam|Thai rum, pineapple, bitters, ginger",
      "Melon Baller|Gin, melon liqueur, lotus roots",
    ],
  ],
  [
    "spice",
    "Spice It Up",
    [
      "A Chaar of Pickles|Sous vide pickle vodka",
      "Leaf Me Alone|Rosemary gin, cha muang leaf, jeera leaf, basil",
      "Roselle Roselle|Whisky, roselle syrup",
      "Wassa-Bae|Wasabi-infused gin, sesame oil, matcha",
      "White Spice|Malibu, galangal, chilli",
      "Khata Teekha Meetha|Whisky, tamarind, chilli",
      "Pandan Peppercorn|Gin, pandan, peppercorn",
      "Chai Whisky|Whisky, chai syrup",
      "Bright Spice|Tequila, jalapeño, capsicum, pomegranate",
      "It Burns|Whisky, sriracha, betel",
    ],
  ],
  [
    "world",
    "Around the World",
    [
      "Chai Whisky|Whisky, homemade chai syrup · India",
      "Cha Yen|Vodka, cha yen · Thailand",
      "Caipirinha|Cachaça, sugar, lime · Brazil",
      "Tej|Wine, honey, mead; served in a teapot · Ethiopia",
      "Aja Mexico Chaliye|Tequila, sangria, lime · Mexico",
      "Pastis|Liqueur flavoured with licorice and aniseed · France",
      "Beer Limoncello|Limoncello, honey, lemon, beer · Italy",
      "LLB|Lemon, lime and bitters · Australia",
      "Masarap|Mango beer mojito · Philippines",
      "OPA|Ouzo · Greece",
    ],
  ],
  [
    "emergency",
    "Emergency Drunk",
    [
      "Just Got Fired|Vodka, beer, Jäger, lychee, cranberry",
      "She Was My Everything|Absinthe, tobacco-infused vodka, honey mustard syrup",
      "I Want to Forget|Cointreau, champagne, plum beer",
      "Existential Crisis|Chartreuse, Campari, Sauvignon Blanc, Sprite",
      "When Will It Stop?|Limoncello, Midori, Benedictine, vanilla vodka, soda",
      "Kal Meri Shaadi Hai|Strawberry soju, pink gin, banana liqueur, raspberry jam, lime",
      "If You’re In, I’m In|Sake, whisky, black pepper syrup, lime",
      "Why Always Me?|Spiced rum, hot sauce, Cointreau, salt, peppermint syrup",
      "Party Toh Abhi Shuru Huyi Hai|Kahlua, cherry brandy, vodka, dry vermouth, cinnamon syrup",
      "The END|Drink water. Go home. Sleep.",
    ],
  ],
  [
    "shocktail",
    "Shocktail",
    [
      "Waterfall|A theatrical serving concept",
      "Syringes|A playful serving prop",
      "Puff-Puff|A presentation concept",
      "Water Guns|A playful serving prop",
      "Buckets|A group serving format",
      "Baraf Ka Gola|An ice-gola serving concept",
      "Slushy Seduction|A slushy serving concept",
      "Fruit Jello|A fruit-jello serving format",
      "Watergun War Zone|A playful event concept",
      "You Are the Garnish|An outdoor inflatable-pool concept",
    ],
  ],
  [
    "food",
    "Once Was Food",
    [
      "The Great Bowl of China|Whisky, rum, orange juice, five spices",
      "Sweet & Sour|Vodka, tomato juice, seafood sauce",
      "Karele Ki Khasthi|Gin, elaichi, curry leaves, bitter gourd",
      "Tandoori Night|Whisky, tomatoes, garam masala, liquid smoke; served in capsicum",
      "Pyaara Palak|Tequila, orgeat, spinach, egg white, ginger, lime",
      "Som Tum Reserve|Vodka, papaya, chilli",
      "Tom Yum|Vodka, lemongrass, galangal, kaffir, chilli",
      "Tom Kha|Rum, coconut, galangal, kaffir",
      "Pizza Party|Vodka, bagel spice mix, marinara sauce, parmesan salt, lime juice, hot sauce, basil/pepperoni",
      "Plump Plum|Japanese plum wine, gin, grape juice",
    ],
  ],
  [
    "warm",
    "Haye Garmi",
    [
      "Mulled Wine|Wine, star anise, cinnamon, strawberry",
      "Nani’s Lemon Tea Recipe|Whisky, honey, ginger, lime",
      "Rum Maro Rum|Dark rum, sesame, ginger tea",
      "Hot Chocolate|Vodka, double cream, chocolate",
      "Irish Coffee|Whisky, coffee, cream",
      "Lakdi Ki Katthi|Thai herbs and wood soaked with rum",
      "Melted Gold|Gin, champagne, saffron",
      "Hot Thai Tea|Vodka, cha ron",
      "Miso Drunky|Japanese gin, orange flower water, miso paste, sesame, seaweed, tofu",
      "Cinnamon Tea|Cinnamon, elderflower, chamomile",
    ],
  ],
  [
    "specialty",
    "13 Reasons High",
    [
      "G&T.HC|THC oil, mango, gin and tonic",
      "Shisha Jam|Vodka, shisha mix, fresh jam",
      "Chilli High|Chilli-infused vodka",
      "2nd Year Breakfast|Coffee and cannabis",
      "Sichuan Cigar|Betel-leaf-infused whisky, tobacco, Sichuan",
      "Cotton Mouth Candy|Cannabis-infused cotton candy",
      "Krathom Kraken|Krathom tea, pineapple, bitters",
      "Caffeinated Cardiac|Champagne, Jäger, coffee",
      "Palan Paan|Vodka, sambuca, paan, chocolate",
      "Supaari Ke Satah Swaagat|Supari-infused rum",
    ],
  ],
  [
    "candy",
    "Candy Cocktails",
    [
      "Kapiko|Candy-inspired cocktail concept",
      "Skittles|Candy-inspired cocktail concept",
      "Fruit Loops|Candy-inspired cocktail concept",
      "Yellow Halls|Candy-inspired cocktail concept",
      "Boomer|Candy-inspired cocktail concept",
      "Wurther Original|Candy-inspired cocktail concept",
      "Olé|Candy-inspired cocktail concept",
      "Pink Berry|Candy-inspired cocktail concept",
      "Himalayan Salt|Candy-inspired cocktail concept",
      "My-Mint|Candy-inspired cocktail concept",
    ],
  ],
  [
    "dessert",
    "Dessert Drinks",
    [
      "Affogato “I Forgot Tho”|Kahlua, vodka, ice cream",
      "Home-made Ice Lollies|Fruits and cream lollies",
      "Pandan Delight|Pandan-infused vodka",
      "Fruit Chaat|Vodka jello, chaat masala, mint",
      "BOBA TEA|Baileys, double cream, Taiwanese tea, boba pearls",
      "Baraf Ka Gola|Indian-style ice cone dipped in an alcoholic syrup of your choice",
      "Rasmalai|Rasmalai soaked in Baileys and elaichi syrup",
      "Shaandaar Sharday|Tequila, pistachio, almond, elaichi, black pepper",
      "Malibu Cake|Malibu-soaked sponge cake",
      "Cup of WhippCREAM|Alcoholic whipped cream",
    ],
  ],
];
export const catalogue = groups.map(([id, name, rows]) => ({
  id,
  name,
  drinks: rows.map((row, index) => {
    const [name, ingredients] = row.split("|");
    return { id: `${id}-${index + 1}`, name, ingredients };
  }),
}));
export const catalogueCount = catalogue.reduce(
  (sum, g) => sum + g.drinks.length,
  0,
);
