export const faqs = [
  { question: "What does Dr. Drunk do?", answer: "Dr. Drunk creates bespoke cocktails and tailored bar experiences, bringing together mixology, glassware, bar setup, flair and hospitality for celebrations.", href: "/experiences", link: "Explore bar experiences" },
  { question: "Can our wedding cocktails tell our story?", answer: "Yes. A first date, favourite trip, proposal or inside joke can inspire the flavours, drink names and presentation. Menus, coasters, stirrers and short story notes can carry the theme across the bar.", href: "/weddings", link: "Discover wedding storytelling" },
  { question: "Where can we explore the cocktail options?", answer: "The cocktail collection contains all 100 entries from the supplied Dr. Drunk menu, organized into ten categories. Search by name or ingredient, then discuss your preferred selections with the team.", href: "/cocktails", link: "Browse the cocktail collection" },
  { question: "Can each wedding function have a different theme?", answer: "Yes. The Dr. Drunk storytelling approach gives Haldi, Sangeet, Wedding and After Party their own mood, with coordinated drinks, glassware, décor, props and costumes.", href: "/weddings#wedding-details", link: "Explore the details" },
  { question: "What should we share when enquiring?", answer: "Send your occasion, event date, location, approximate guest count, favourite flavours and any moodboard or story ideas. These details help the team shape the first conversation.", href: "/contact", link: "Start planning your bar" },
  { question: "How do we arrange a tasting or video call?", answer: "Use the tasting link to open a prepared email to Docdrunkofficial@gmail.com, or call +66 6-2643-9728 or +66 9-2417-2299. The team can discuss an appointment or video call with you.", href: "/contact#appointment", link: "Contact the practice" },
  { question: "Are prices and availability shown online?", answer: "This website is a collection of ideas and services. Confirm your event date, location, menu, service scope and pricing directly with the team before making plans. Sending an enquiry does not confirm a booking.", href: "/contact", link: "Discuss your occasion" },
  { question: "Where can we see real events and the original guides?", answer: "The gallery includes 50 supplied event photographs. The About page links to the original company profile, cocktail menu, storytelling guide and concept, entertainment and flair boards.", href: "/about#guides", link: "Open the original guides" },
];
